### PR TITLE
fix: fix showing children first issue

### LINKED ISSUE #146: Fix showing children before create wallet page bug

### PR DESCRIPTION
**Pull request by su-de-sh**

### CODE REVIEW

File: src/guards/AuthGuard.js [hunk 1]
```diff
@@ -16,12 +16,31 @@ AuthGuard.propTypes = {
...
+//     }
+//     // eslint-disable-next-line react-hooks/exhaustive-deps
+//   }, [isAuthenticated, isInitialized]);
+
+//   if (!isInitialized) {
+//     return <LoadingScreen />;
+//   }
+
+//   return <>{children}</>;
+// }
```
Comment (rushilshakya) [inline src/guards/AuthGuard.js]: remove comment

**Review by rushilshakya — APPROVED** [review]
